"""
Two Opposite-Polarity Magnets - Complete Workflow Example
==========================================================

This is a self-contained training example that demonstrates the COMPLETE GetDP 
magnetostatic FEA workflow from scratch:

1. Create geometry (.geo file)
2. Generate mesh (.msh file) 
3. Run FEA solver (.pro file)
4. Visualize results in Gmsh

The example creates two permanent magnets with opposite polarity in air:
- Left magnet: 30mm x 30mm, magnetization +Y direction
- Right magnet: 30mm x 30mm, magnetization -Y direction (opposite)
- Shows magnetic field interaction between opposing magnets
- Demonstrates proper B-field propagation through air
- Complete spherical shell boundary (required by GetDP library)

This tests magnet-to-magnet field interaction without a steel core.
"""

import subprocess
import os
import sys

# Add src to path for gmsh/getdp executables
script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(script_dir)
src_dir = os.path.join(repo_root, 'src')

# Paths to executables
getdp_dir = os.path.join(src_dir, 'getdp-3.5.0-Windows64')
getdp_exe = os.path.join(getdp_dir, 'getdp.exe')
getdp_templates = os.path.join(getdp_dir, 'templates')
gmsh_exe = os.path.join(src_dir, 'gmsh', 'gmsh.exe')

# Working directory for this example
work_dir = os.path.join(script_dir, 'c_core_output')

def create_geometry():
    """
    Step 1: Create the geometry file (.geo)
    
    Defines two permanent magnets with opposite polarity:
    - Left magnet: 30mm x 30mm at x=-70mm to -40mm, magnetization +Y
    - Right magnet: 30mm x 30mm at x=+40mm to +70mm, magnetization -Y
    - Inner air region: from magnets to R=150mm
    - Spherical shell: R=150mm to R=250mm (required by GetDP library)
    - Complete circular boundaries (top and bottom halves)
    - Uniform mesh size in both magnets for consistent solution
    """
    
    print("=" * 60)
    print("Step 1: Creating Geometry")
    print("=" * 60)
    print()
    
    # Create output directory
    os.makedirs(work_dir, exist_ok=True)
    
    geo_file = os.path.join(work_dir, 'c_core.geo')
    
    geo_content = """// Two Opposite-Polarity Magnets in Air
// Generated by test_baseline_2.py

// Geometry parameters
h = 0.14;      // Reference dimension (m)
l = 0.14;      // Reference dimension (m)
d = 0.03;      // Magnet thickness (m)
e = 5e-3;      // Reference dimension (m)
ha = 0.03;     // Magnet height (m)

Val_Rint = 0.15;  // Internal shell radius
Val_Rext = 0.25;  // External shell radius

// Mesh size parameters
lc0 = d / 5;
lc1 = e / 2;
lc2 = (Val_Rext - Val_Rint) / 8.;

// Points - Left magnet (30mm x 30mm, magnetization +Y)
Point(1) = {0, 0, 0, lc0};
Point(2) = {-l/2, 0, 0, lc0};
Point(6) = {-l/2, ha/2, 0, lc0};
Point(7) = {-l/2+d, ha/2, 0, lc0};
Point(8) = {-l/2+d, 0, 0, lc0};
Point(4) = {l/2, 0, 0, lc0};

// Points - Right magnet (30mm x 30mm, magnetization -Y, opposite polarity)
Point(9) = {l/2-d, 0, 0, lc0};
Point(12) = {l/2, ha/2, 0, lc0};
Point(13) = {l/2-d, ha/2, 0, lc0};

// Points - Spherical shell (infinite boundary)
Point(30) = {Val_Rint, 0, 0, lc2};
Point(31) = {Val_Rext, 0, 0, lc2};
Point(32) = {0, Val_Rint, 0, lc2};
Point(33) = {0, Val_Rext, 0, lc2};
Point(34) = {-Val_Rext, 0, 0, lc2};
Point(35) = {-Val_Rint, 0, 0, lc2};
Point(36) = {0, -Val_Rint, 0, lc2};
Point(37) = {0, -Val_Rext, 0, lc2};

// Lines - Geometry connections
Line(1) = {34, 35};  // Outer left to inner left (connection line)
Line(2) = {35, 2};
Line(3) = {2, 8};
Line(4) = {8, 1};
Line(5) = {1, 9};
Line(6) = {9, 4};
Line(7) = {4, 30};  // Connect to inner right
Line(8) = {30, 31};  // Inner right to outer right (connection line)
Line(9) = {2, 6};
Line(18) = {7, 8};
Line(19) = {7, 6};

// Lines - Right magnet
Line(14) = {9, 13};
Line(20) = {13, 12};
Line(13) = {12, 4};

// Circles - Spherical shell boundaries (complete circles)
Circle(21) = {35, 1, 32};  // Inner left to top
Circle(22) = {32, 1, 30};  // Inner top to right
Circle(23) = {30, 1, 36};  // Inner right to bottom
Circle(24) = {36, 1, 35};  // Inner bottom to left
Circle(25) = {34, 1, 33};  // Outer left to top
Circle(26) = {33, 1, 31};  // Outer top to right
Circle(27) = {31, 1, 37};  // Outer right to bottom
Circle(28) = {37, 1, 34};  // Outer bottom to left

// Surfaces
Line Loop(40) = {21, 22, 23, 24};  // Inner circle (complete)
Line Loop(41) = {25, 26, 27, 28};  // Outer circle (complete)
Plane Surface(42) = {41, 40};  // Spherical shell (annular region)

// Air region with both magnets as holes
Line Loop(43) = {19, -9, 3, -18};  // Left magnet outline (hole)
Line Loop(44) = {20, 13, -6, 14};  // Right magnet outline (hole)
Line Loop(45) = {2, 9, -19, 18, 4, 5, 6, 7, -22, -21};  // Outer air boundary to inner circle (top half)
Plane Surface(46) = {45, 43, 44};  // Air with both magnets cutout

// Left Magnet (magnetization +Y)
Line Loop(47) = {19, -9, 3, -18};
Plane Surface(48) = {47};  // Left magnet

// Right Magnet (magnetization -Y, opposite polarity)
Line Loop(49) = {20, 13, -6, 14};
Plane Surface(50) = {49};  // Right magnet

// Duplicate geometry across y=0 to create full problem
out_air[] = Symmetry {0, 1, 0, 0} { Duplicata { Surface{46}; } };
out_magnet_left[] = Symmetry {0, 1, 0, 0} { Duplicata { Surface{48}; } };
out_magnet_right[] = Symmetry {0, 1, 0, 0} { Duplicata { Surface{50}; } };

// Physical entities - including both original and duplicated surfaces
Physical Surface("Air", 100) = {46, out_air[0]};
Physical Surface("Spherical shell", 101) = {42};
Physical Surface("Magnet_Left", 102) = {48, out_magnet_left[0]};
Physical Surface("Magnet_Right", 103) = {50, out_magnet_right[0]};
Physical Line("Exterior boundary", 104) = {25, 26, 27, 28};

// Mesh display options - color by physical groups
Mesh.ColorCarousel = 2;  // Color by physical group
Mesh.SurfaceEdges = 1;   // Show surface edges
Mesh.SurfaceFaces = 2;   // Color faces by physical entity
"""
    
    with open(geo_file, 'w') as f:
        f.write(geo_content)
    
    print(f"✓ Geometry file created: {geo_file}")
    print(f"  Magnet: {30}mm x {30}mm")
    print(f"  Shell: R={150}mm to {250}mm")
    print()
    
    return geo_file

def generate_mesh(geo_file):
    """
    Step 2: Generate finite element mesh (.msh)
    
    Uses Gmsh to create a 2D triangular mesh from the geometry.
    Mesh is refined in critical areas:
    - Medium mesh in magnets (6mm elements, uniform in both)
    - Medium mesh in inner air region (6mm elements)  
    - Coarse mesh in spherical shell (18.75mm elements)
    """
    
    print("=" * 60)
    print("Step 2: Generating Mesh")
    print("=" * 60)
    print()
    
    if not os.path.exists(gmsh_exe):
        print(f"ERROR: Gmsh executable not found at {gmsh_exe}")
        return None
    
    msh_file = os.path.join(work_dir, 'c_core.msh')
    
    print("Running Gmsh mesher...")
    print(f"Input: {os.path.basename(geo_file)}")
    print(f"Output: {os.path.basename(msh_file)}")
    print()
    
    try:
        result = subprocess.run(
            [gmsh_exe, geo_file, '-2', '-o', msh_file],
            cwd=work_dir,
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if result.returncode != 0:
            print("Gmsh Errors:")
            print(result.stderr)
            return None
        
        if os.path.exists(msh_file):
            filesize = os.path.getsize(msh_file)
            print(f"✓ Mesh generated: {os.path.basename(msh_file)} ({filesize:,} bytes)")
            
            # Parse mesh info from output
            if "nodes" in result.stdout.lower():
                for line in result.stdout.split('\n'):
                    if 'nodes' in line.lower() or 'elements' in line.lower():
                        print(f"  {line.strip()}")
            
            print()
            return msh_file
        else:
            print("ERROR: Mesh file not created")
            return None
            
    except subprocess.TimeoutExpired:
        print("ERROR: Gmsh timed out after 30 seconds")
        return None
    except Exception as e:
        print(f"ERROR running Gmsh: {e}")
        return None

def create_solver_file():
    """
    Step 3: Create GetDP solver input file (.pro)
    
    Defines the magnetostatic problem:
    - Material properties (μr=1 for air and magnets)
    - Left magnet: Hc = 920 kA/m in +Y direction
    - Right magnet: Hc = 920 kA/m in -Y direction (opposite polarity)
    - Boundary conditions (a=0 on outer boundary)
    - Uses GetDP library template for formulation
    - Post-processing: magnetic vector potential, B-field, H-field
    """
    
    print("=" * 60)
    print("Step 3: Creating Solver Input File")
    print("=" * 60)
    print()
    
    pro_file = os.path.join(work_dir, 'c_core.pro')
    
    # Create the solver file using GetDP library template
    pro_content = f"""// Two Magnets with Opposite Polarity - No Core
// Generated by test_baseline_2.py

// Constants for spherical shell (required by library template)
DefineConstant[ Val_Rint = 0.15 ];  // Internal shell radius (m)
DefineConstant[ Val_Rext = 0.25 ];  // External shell radius (m)

// Region tags (must match geometry Physical entities)
AIR = 100;
AIR_INF = 101;
MAGNET_LEFT = 102;
MAGNET_RIGHT = 103;
LINE_INF = 104;

Group {{
  Air     = Region[ AIR ];
  AirInf  = Region[ AIR_INF ];
  Magnet_Left  = Region[ MAGNET_LEFT ];
  Magnet_Right = Region[ MAGNET_RIGHT ];
  Dirichlet_a_0   = Region[ LINE_INF ];
  Dirichlet_phi_0 = Region[ LINE_INF ];

  // Generic group names for library template
  Vol_Mag = Region[ {{Air, AirInf, Magnet_Left, Magnet_Right}} ];
  Vol_Inf_Mag = Region[ AirInf ];
  Vol_M_Mag   = Region[ {{Magnet_Left, Magnet_Right}} ];
}}

Function {{
  mu0 = 4.e-7 * Pi;
  
  // Material properties - all air and magnets
  nu [ Region[{{Air, AirInf, Magnet_Left, Magnet_Right}}] ] = 1. / mu0;
  mu [ Region[{{Air, AirInf, Magnet_Left, Magnet_Right}}] ] = mu0;
  
  // Permanent magnet coercive fields (opposite directions)
  Hc = 920000;  // A/m (NdFeB grade)
  hc [ Magnet_Left ] = Rotate[ Vector[Hc, 0, 0.], 0, 0, Pi/2];      // Points +Y
  hc [ Magnet_Right ] = Rotate[ Vector[Hc, 0, 0.], 0, 0, -Pi/2];    // Points -Y (opposite)
}}

// Boundary conditions
Constraint {{
  {{ Name a;
    Case {{
      {{ Region Dirichlet_a_0; Value 0.; }}
    }}
  }}
  {{ Name phi;
    Case {{
      {{ Region Dirichlet_phi_0; Value 0.; }}
    }}
  }}
}}

// Include magnetostatic formulation from GetDP library
Include "{getdp_templates}/Lib_Magnetostatics_a_phi.pro"

// Post-processing operations
eps = 1.e-5;
PostOperation {{
  {{ Name MagnetostaticsSolution; NameOfPostProcessing Magnetostatics_a;
    Operation {{
      Print[ az, OnElementsOf Vol_Mag, File "c_core_az.pos"];
      Print[ b, OnElementsOf Vol_Mag, File "c_core_b.pos"];
      Print[ h, OnElementsOf Vol_Mag, File "c_core_h.pos"];
    }}
  }}
}}
"""
    
    with open(pro_file, 'w', encoding='utf-8') as f:
        f.write(pro_content)
    
    print(f"✓ Solver file created: {pro_file}")
    print(f"  Formulation: Magnetostatics (vector potential)")
    print(f"  Materials: Air (μr=1), Magnets (μr=1)")
    print(f"  Coercive field: Hc = 920 kA/m")
    print(f"  Left magnet: +Y direction")
    print(f"  Right magnet: -Y direction (opposite polarity)")
    print(f"  Boundary: a=0 on outer shell")
    print()
    
    return pro_file

def run_solver(pro_file, msh_file):
    """
    Step 4: Run GetDP magnetostatic solver
    
    Solves the magnetostatic problem using finite element method.
    The solver assembles the global stiffness matrix and solves
    the linear system to find the magnetic vector potential.
    
    Expected convergence: residual < 1e-9
    """
    
    print("=" * 60)
    print("Step 4: Running FEA Solver")
    print("=" * 60)
    print()
    
    if not os.path.exists(getdp_exe):
        print(f"ERROR: GetDP executable not found at {getdp_exe}")
        return False
    
    print("Running GetDP magnetostatic solver...")
    print(f"Problem file: {os.path.basename(pro_file)}")
    print(f"Mesh file: {os.path.basename(msh_file)}")
    print()
    
    try:
        result = subprocess.run(
            [getdp_exe, os.path.basename(pro_file), '-msh', os.path.basename(msh_file),
             '-solve', 'Magnetostatics_a', '-pos', 'MagnetostaticsSolution'],
            cwd=work_dir,
            capture_output=True,
            text=True,
            timeout=60
        )
        
        print("GetDP Output:")
        print("-" * 60)
        print(result.stdout)
        
        if result.returncode != 0:
            print("GetDP Errors:")
            print(result.stderr)
            return False
        
        print("-" * 60)
        print()
        
        # Check for output files
        output_files = ['c_core_az.pos', 'c_core_b.pos', 'c_core_h.pos']
        missing_files = []
        
        for filename in output_files:
            filepath = os.path.join(work_dir, filename)
            if os.path.exists(filepath):
                filesize = os.path.getsize(filepath)
                print(f"✓ Generated: {filename} ({filesize:,} bytes)")
            else:
                missing_files.append(filename)
                print(f"✗ Missing: {filename}")
        
        if missing_files:
            print(f"\nWARNING: {len(missing_files)} output files missing")
            return False
        
        print()
        print("=" * 60)
        print("SUCCESS: Magnetostatic solution completed")
        print("=" * 60)
        print()
        
        return True
        
    except subprocess.TimeoutExpired:
        print("ERROR: GetDP timed out after 60 seconds")
        return False
    except Exception as e:
        print(f"ERROR running GetDP: {e}")
        return False

def visualize_results():
    """
    Step 5: Visualize results in Gmsh
    
    Opens two Gmsh viewers:
    1. Mesh visualization - shows geometry and mesh refinement
    2. B-field visualization - shows magnetic flux density distribution
    
    Expected results:
    - High B-field in both magnets (~1 T)
    - Field lines flow from left magnet (+Y) to right magnet (-Y)
    - Field propagates through air between magnets
    - Field decreases in far-field air
    - Demonstrates opposing magnet interaction
    """
    
    print("=" * 60)
    print("Step 5: Visualizing Results")
    print("=" * 60)
    print()
    
    mesh_file = os.path.join(work_dir, 'c_core.msh')
    b_field_file = os.path.join(work_dir, 'c_core_b.pos')
    
    if not os.path.exists(mesh_file):
        print("ERROR: Mesh file not found")
        return False
    
    if not os.path.exists(b_field_file):
        print("ERROR: B-field output file not found")
        return False
    
    if not os.path.exists(gmsh_exe):
        print(f"ERROR: Gmsh executable not found at {gmsh_exe}")
        return False
    
    print("Opening visualizations in Gmsh...")
    print()
    
    # Create a visualization script for proper mesh coloring
    view_script = os.path.join(work_dir, 'view_mesh.geo')
    with open(view_script, 'w') as f:
        f.write(f'''// Load mesh
Merge "{mesh_file}";

// Set visualization options to color by physical group
Mesh.ColorCarousel = 2;  // Color by physical entity number
Mesh.SurfaceEdges = 1;   // Show edges
Mesh.SurfaceFaces = 2;   // Color faces by elementary entity
Mesh.VolumeEdges = 0;    // Don't show volume edges

// Display options
General.Trackball = 0;
General.RotationX = 0;
General.RotationY = 0;
General.RotationZ = 0;
''')
    
    try:
        # Open mesh viewer with visualization script
        print("Launching mesh viewer...")
        subprocess.Popen([gmsh_exe, view_script], cwd=work_dir)
        print("✓ Mesh viewer launched")
        print()
        
        # Small delay
        import time
        time.sleep(0.5)
        
        # Open B-field viewer
        print("Launching B-field viewer...")
        print("Look for field distribution:")
        print("  - Magnet: High B-field (~1 T)")
        print("  - Air gap: Field propagates")
        print("  - Steel core: Concentrated field (2-3 T)")
        print("  - Surrounding air: Decreasing field")
        subprocess.Popen([gmsh_exe, b_field_file], cwd=work_dir)
        print("✓ B-field viewer launched")
        print()
        
        return True
        
    except Exception as e:
        print(f"ERROR launching Gmsh: {e}")
        return False

def main():
    """
    Main execution - Complete workflow
    
    Executes all steps:
    1. Create geometry (.geo)
    2. Generate mesh (.msh)
    3. Create solver file (.pro)
    4. Run GetDP solver
    5. Visualize results
    """
    
    print("\n")
    print("*" * 60)
    print("Two Opposite-Polarity Magnets - COMPLETE WORKFLOW")
    print("Geometry → Mesh → Solve → Visualize")
    print("*" * 60)
    print("\n")
    
    # Step 1: Create geometry
    geo_file = create_geometry()
    if not geo_file:
        print("\n❌ Failed to create geometry")
        return 1
    
    # Step 2: Generate mesh
    msh_file = generate_mesh(geo_file)
    if not msh_file:
        print("\n❌ Failed to generate mesh")
        return 1
    
    # Step 3: Create solver file
    pro_file = create_solver_file()
    if not pro_file:
        print("\n❌ Failed to create solver file")
        return 1
    
    # Step 4: Run solver
    success = run_solver(pro_file, msh_file)
    if not success:
        print("\n❌ Solver failed - see errors above")
        return 1
    
    # Step 5: Visualize
    visualize_results()
    
    print("\n" + "*" * 60)
    print("COMPLETE WORKFLOW FINISHED SUCCESSFULLY!")
    print("*" * 60)
    print()
    print(f"All files saved to: {work_dir}")
    print()
    print("Key Workflow Steps:")
    print("1. ✓ Geometry created (.geo file)")
    print("2. ✓ Mesh generated (.msh file)")
    print("3. ✓ Solver input created (.pro file)")
    print("4. ✓ FEA solution computed")
    print("5. ✓ Results visualized in Gmsh")
    print()
    print("This demonstrates the complete GetDP workflow from scratch!")
    print()
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
